# Generated by Django 6.0.7 on 2026-08-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_certification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteContent',
            new_name='Site_Home_Content',
        ),
    ]
