# Generated by Django 6.0.7 on 2026-08-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_site_admin_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site_Admin_Content',
            new_name='Site_About_Content',
        ),
    ]
