# Generated by Django 6.0.7 on 2026-08-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_solution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='long_description',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='short_description',
            new_name='summary',
        ),
    ]
