# Generated by Django 6.0.7 on 2026-08-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_long_description_solution_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='name',
            new_name='title',
        ),
    ]
