# Generated by Django 6.0.7 on 2026-08-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_termsandconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandconditions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
