# Generated by Django 6.0.7 on 2026-08-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_productspecification_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='note',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='role',
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(default='brands/default-logo.png', upload_to='brands/'),
        ),
    ]
