# Generated by Django 6.0.7 on 2026-08-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_productcategory_productsubcategory_producttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Calibration_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
            ],
        ),
    ]
