# Generated by Django 6.0.7 on 2026-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_site_calibration_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration_Capabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='calibration_capabilities/')),
            ],
            options={
                'verbose_name': 'Calibration Capability',
                'verbose_name_plural': 'Calibration Capabilities',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Calibration_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='calibration_services/')),
            ],
            options={
                'verbose_name': 'Calibration Service',
                'verbose_name_plural': 'Calibration Services',
                'ordering': ['order', 'title'],
            },
        ),
    ]
