# Generated by Django 6.0.7 on 2026-08-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_calibration_capabilities_calibration_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
