# Generated by Django 6.0.7 on 2026-08-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_company_details_site_base_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_milestone_content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_content/'),
        ),
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_content/'),
        ),
        migrations.AddField(
            model_name='company_details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_content/'),
        ),
        migrations.AddField(
            model_name='site_about_content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_content/'),
        ),
        migrations.AddField(
            model_name='site_base_content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_content/'),
        ),
        migrations.AddField(
            model_name='site_calibration_content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_content/'),
        ),
        migrations.AddField(
            model_name='site_home_content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_content/'),
        ),
        migrations.AddField(
            model_name='site_product_content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_content/'),
        ),
        migrations.AddField(
            model_name='site_project_content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_content/'),
        ),
        migrations.AddField(
            model_name='site_solutions_content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_content/'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_content/'),
        ),
        migrations.AddField(
            model_name='termsandconditions_content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_content/'),
        ),
    ]
