# Generated by Django 6.0.7 on 2026-08-11 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_about_milestone_content_image_certification_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_details',
            name='image',
        ),
        migrations.RemoveField(
            model_name='site_about_content',
            name='image',
        ),
        migrations.RemoveField(
            model_name='site_base_content',
            name='image',
        ),
        migrations.RemoveField(
            model_name='site_calibration_content',
            name='image',
        ),
        migrations.RemoveField(
            model_name='site_product_content',
            name='image',
        ),
        migrations.RemoveField(
            model_name='site_project_content',
            name='image',
        ),
        migrations.RemoveField(
            model_name='site_solutions_content',
            name='image',
        ),
        migrations.RemoveField(
            model_name='termsandconditions_content',
            name='image',
        ),
    ]
