# Generated by Django 6.0.7 on 2026-08-11 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_company_details_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_home_content',
            name='image',
        ),
    ]
