# Generated by Django 6.0.7 on 2026-08-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_site_home_content_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_About_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='about/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
