# Generated by Django 6.0.7 on 2026-08-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_site_about_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site_About_Image',
        ),
    ]
