# Generated by Django 6.0.7 on 2026-08-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_delete_site_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Image_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('background_image', models.ImageField(upload_to='home/hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
