# Generated by Django 6.0.7 on 2026-08-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_home_image_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home_Image_Content',
        ),
    ]
